nelmio_api_doc:
  documentation:
    info:
      title: "Mon API Symfony"
      description: "Documentation de mon API avec Swagger"
      version: "1.0.0"
  areas:
    path_patterns: # Définir les routes à inclure dans la documentation
      - ^/api # Cela inclut toutes les routes commençant par /api